spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://restfull-api.c10uu7znqkvd.eu-west-1.rds.amazonaws.com:3306/restfull_api?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: /Users/JoãoCarlosPereira/Documents/uploads

spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
cors:
  originPatterns: http://localhost:8080, http://localhost:3000

security:
  jwt:
    token:
      secret-key: secretkey
      expire-length: 3600000

flyway:
  url: jdbc:mysql://localhost:3306/
  schemas: rest_with_spring_boot_udemy
  user: root
  password: root
server:
  port: 8080